#!/bin/bash

set -o pipefail

# This is the log file we're interested in
logfile="/etc/logs/error.log"

echo "Number of times each error message appears:"
cat "${logfile}" | grep "ERROR" | sort  | uniq  -c

exit 0
